#This needs to match your custom fabric baseimage if you are changing that
FROM bff0b31446af 
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
ENV PEER_CFG_PATH /etc/hyperledger/fabric
RUN mkdir -p /var/hyperledger/db $PEER_CFG_PATH/msp
COPY payload/peer /usr/local/bin
COPY payload/core.yaml $PEER_CFG_PATH
COPY payload/peer-config.json $PEER_CFG_PATH/msp
CMD peer node start
